// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}

type Category struct {
	ID        int64              `json:"id"`
	Name      pgtype.Text        `json:"name"`
	Desc      pgtype.Text        `json:"desc"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        int64              `json:"id"`
	Content   pgtype.Text        `json:"content"`
	PostID    pgtype.Int4        `json:"post_id"`
	UserID    pgtype.Int4        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	PostID    pgtype.Int8        `json:"post_id"`
	UserID    pgtype.Int8        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Follow struct {
	FollowingUserID pgtype.Int4        `json:"following_user_id"`
	FollowedUserID  pgtype.Int4        `json:"followed_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID          int64              `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Content     pgtype.Text        `json:"content"`
	ReferenceID pgtype.Int8        `json:"reference_id"`
	UserID      pgtype.Int8        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID         int64              `json:"id"`
	Title      pgtype.Text        `json:"title"`
	Content    pgtype.Text        `json:"content"`
	Image      pgtype.Text        `json:"image"`
	UserID     pgtype.Int4        `json:"user_id"`
	CategoryID pgtype.Int4        `json:"category_id"`
	Status     pgtype.Text        `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Rating struct {
	Rate      pgtype.Int4        `json:"rate"`
	PostID    pgtype.Int8        `json:"post_id"`
	UserID    pgtype.Int8        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Avatar    pgtype.Text        `json:"avatar"`
	Username  pgtype.Text        `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
